<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11766" started-at="2021-01-14T14:38:54Z" finished-at="2021-01-14T14:39:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11766" started-at="2021-01-14T14:38:54Z" finished-at="2021-01-14T14:39:06Z">
      <class name="com.qa.fdcalculator.testcase.SIcalculation2">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.fdcalculator.testcase.SIcalculation2@6a41eaa2]" name="setup" is-config="true" duration-ms="11348" started-at="2021-01-14T14:38:54Z" finished-at="2021-01-14T14:39:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="calculationSI()[pri:0, instance:com.qa.fdcalculator.testcase.SIcalculation2@6a41eaa2]" name="calculationSI" duration-ms="331" started-at="2021-01-14T14:39:05Z" finished-at="2021-01-14T14:39:06Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.qa.utiles.dbOperation.createstatement(dbOperation.java:42)
at com.qa.utiles.dbOperation.executequery(dbOperation.java:74)
at com.qa.fdcalculator.testcase.SIcalculation2.calculationSI(SIcalculation2.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- calculationSI -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.qa.fdcalculator.testcase.SIcalculation2@6a41eaa2]" name="tear" is-config="true" duration-ms="61" started-at="2021-01-14T14:39:06Z" finished-at="2021-01-14T14:39:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.qa.fdcalculator.testcase.SIcalculation2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
